// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXOlolPNbeSD_e8dVvTINOcz1ahBVtle0',
    appId: '1:272623175483:web:e747afe0579ee266f6191e',
    messagingSenderId: '272623175483',
    projectId: 'hraj-hd5',
    authDomain: 'hraj-hd5.firebaseapp.com',
    storageBucket: 'hraj-hd5.firebasestorage.app',
    measurementId: 'G-C2ZJ940WX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6_U-0lvr38Ydlm2bfjEO00Fb2YT2gMM',
    appId: '1:272623175483:android:eeeb304dc1d8be07f6191e',
    messagingSenderId: '272623175483',
    projectId: 'hraj-hd5',
    storageBucket: 'hraj-hd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD815YqbLxyWJjbdf0SGwj20HOknSbRSZw',
    appId: '1:272623175483:ios:a276f3ab990a7ef0f6191e',
    messagingSenderId: '272623175483',
    projectId: 'hraj-hd5',
    storageBucket: 'hraj-hd5.firebasestorage.app',
    iosBundleId: 'com.example.yeHraj',
  );

}