// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqQWthUuKHNwmtSJFwPoDz497yJja8p4E',
    appId: '1:184368422258:web:d80b7ec386b2f475da11eb',
    messagingSenderId: '184368422258',
    projectId: 'hraj-ye5',
    authDomain: 'hraj-ye5.firebaseapp.com',
    storageBucket: 'hraj-ye5.firebasestorage.app',
    measurementId: 'G-8SJ8TE5BEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcjp6gFxDN2xeeWzazRs2ws8FnbdYSZo',
    appId: '1:184368422258:android:9fbcc2a4c64162eada11eb',
    messagingSenderId: '184368422258',
    projectId: 'hraj-ye5',
    storageBucket: 'hraj-ye5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACo6vOspkq0o-PWBYCxNN7ye8i8Q7vfCo',
    appId: '1:184368422258:ios:e18aa88b0223a9b5da11eb',
    messagingSenderId: '184368422258',
    projectId: 'hraj-ye5',
    storageBucket: 'hraj-ye5.firebasestorage.app',
    iosBundleId: 'com.example.yeHraj',
  );
}
